name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-electron:
    name: Build Electron App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Install root dependencies
        run: npm install

      - name: Build application
        run: npm run build:electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename electron app for distribution
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Find the Squirrel installer and rename it
            find out/make -name "*.exe" -not -path "*/make-*/*" -exec mv {} out/make/DeepRead-App-Windows-${{ github.ref_name }}.exe \;
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Find the DMG and rename it
            find out/make -name "*.dmg" -exec mv {} out/make/DeepRead-App-macOS-${{ github.ref_name }}.dmg \;
          else
            # Find the deb and rename it
            find out/make -name "*.deb" -exec mv {} out/make/DeepRead-App-Linux-${{ github.ref_name }}.deb \;
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: out/make/DeepRead-App-*-${{ github.ref_name }}.*

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version in package.json files
        run: |
          # Update npm-package.json with the version
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" npm-package.json
          # Update frontend package.json
          cd frontend && npm version $VERSION --no-git-tag-version

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Create npm package
        run: |
          # Create a dist directory for the npm package
          mkdir -p npm-dist/frontend
          mkdir -p npm-dist/bin
          
          # Copy necessary files
          cp -r frontend/dist/* npm-dist/frontend/
          cp bin/deepread.js npm-dist/bin/
          cp npm-package.json npm-dist/package.json
          cp README.md npm-dist/
          cp LICENSE npm-dist/ || touch npm-dist/LICENSE

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd npm-dist
          npm publish --access public

  create-release:
    name: Create GitHub Release
    needs: [build-electron, publish-npm]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/electron-macos-latest/DeepRead-App-macOS-${{ github.ref_name }}.dmg
            artifacts/electron-windows-latest/DeepRead-App-Windows-${{ github.ref_name }}.exe
            artifacts/electron-ubuntu-latest/DeepRead-App-Linux-${{ github.ref_name }}.deb
          body: |
            ## DeepRead ${{ github.ref_name }}

            ### Desktop Apps
            - macOS: [DeepRead-App-macOS-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-macOS-${{ github.ref_name }}.dmg)
            - Windows: [DeepRead-App-Windows-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-Windows-${{ github.ref_name }}.exe)
            - Linux: [DeepRead-App-Linux-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-Linux-${{ github.ref_name }}.deb)

            ### npm Package
            The package is also available on npm:
            ```
            npm install -g deepread@${{ env.VERSION }}
            ```
