name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-electron:
    name: Build Electron App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Install root dependencies
        run: npm install

      - name: Install app dependencies
        run: cd app && npm install

      - name: Update version in package.json for Electron
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" app/package.json
          sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

      - name: Build application
        run: npm run build:electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename electron app for distribution
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Find the Squirrel installer and rename it
            INSTALLER=$(find out/make -name "*.exe" -not -path "*/make-*/*" | head -n 1)
            if [ -n "$INSTALLER" ]; then
              mv "$INSTALLER" out/make/DeepRead-App-Windows-${{ github.ref_name }}.exe
            else
              echo "Warning: Windows installer not found"
              exit 1
            fi
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Find the DMG and rename it
            DMG=$(find out/make -name "*.dmg" | head -n 1)
            if [ -n "$DMG" ]; then
              mv "$DMG" out/make/DeepRead-App-macOS-${{ github.ref_name }}.dmg
            else
              echo "Warning: macOS DMG not found"
              exit 1
            fi
          else
            # Find the deb and rename it
            DEB=$(find out/make -name "*.deb" | head -n 1)
            if [ -n "$DEB" ]; then
              mv "$DEB" out/make/DeepRead-App-Linux-${{ github.ref_name }}.deb
            else
              echo "Warning: Linux DEB not found"
              exit 1
            fi
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: out/make/DeepRead-App-*-${{ github.ref_name }}.*

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version in package.json files
        run: |
          sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" bin/package.json

      - name: Install dependencies
        run: npm run setup

      - name: Build and publish npm package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Build the package using the build:bin script
          npm run build:bin
          # Publish the package
          cd bin
          npm publish --access public

  create-release:
    name: Create GitHub Release
    needs: [build-electron, publish-npm]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.publish-npm.outputs.version }}

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/electron-macos-latest/DeepRead-App-macOS-${{ github.ref_name }}.dmg
            artifacts/electron-windows-latest/DeepRead-App-Windows-${{ github.ref_name }}.exe
            artifacts/electron-ubuntu-latest/DeepRead-App-Linux-${{ github.ref_name }}.deb
          body: |
            ## DeepRead ${{ github.ref_name }}

            ### Desktop Apps
            - macOS: [DeepRead-App-macOS-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-macOS-${{ github.ref_name }}.dmg)
            - Windows: [DeepRead-App-Windows-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-Windows-${{ github.ref_name }}.exe)
            - Linux: [DeepRead-App-Linux-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-Linux-${{ github.ref_name }}.deb)

            ### npm Package
            The package is also available on npm:
            ```
            npm install -g @qnkhuat/deepread@${{ env.VERSION }}
            ```
