name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-electron:
    name: Build Electron App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Install root dependencies
        run: npm install

      - name: Build application
        run: npm run build:electron

      - name: Rename electron app for distribution
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Find the installer and rename it
            find dist -name "*.exe" -exec mv {} dist/DeepRead-App-Windows-${{ github.ref_name }}.exe \;
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Find the DMG and rename it
            find dist -name "*.dmg" -exec mv {} dist/DeepRead-App-macOS-${{ github.ref_name }}.dmg \;
          else
            # Find the AppImage and rename it
            find dist -name "*.AppImage" -exec mv {} dist/DeepRead-App-Linux-${{ github.ref_name }}.AppImage \;
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: dist/*

  build-binary:
    name: Build Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
          python -m pip install virtualenv

      - name: Build Python executable
        run: npm run build:executable

      - name: Rename executable for distribution
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv backend/dist/backend.exe backend/dist/DeepRead-binary-Windows-${{ github.ref_name }}.exe
          else
            mv backend/dist/backend backend/dist/DeepRead-binary-$(if [[ "${{ matrix.os }}" == "macos-latest" ]]; then echo "macOS"; else echo "Linux"; fi)-${{ github.ref_name }}
            if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
              chmod +x backend/dist/DeepRead-binary-macOS-${{ github.ref_name }}
            fi
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: backend/dist/DeepRead-binary-*-${{ github.ref_name }}*

  create-release:
    name: Create GitHub Release
    needs: [build-electron, build-binary]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: List specific files to be uploaded
        run: |
          find artifacts -type f -name "*${{ github.ref_name }}*" -o -name "*.dmg" -o -name "*.exe" -o -name "*.AppImage"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/electron-macos-latest/DeepRead-App-macOS-${{ github.ref_name }}.dmg
            artifacts/electron-windows-latest/DeepRead-App-Windows-${{ github.ref_name }}.exe
            artifacts/electron-ubuntu-latest/DeepRead-App-Linux-${{ github.ref_name }}.AppImage
            artifacts/binary-macos-latest/DeepRead-binary-macOS-${{ github.ref_name }}
            artifacts/binary-windows-latest/DeepRead-binary-Windows-${{ github.ref_name }}.exe
            artifacts/binary-ubuntu-latest/DeepRead-binary-Linux-${{ github.ref_name }}
          body: |
            ## DeepRead ${{ github.ref_name }}

            ### Electron Apps
            - macOS: [DeepRead-App-macOS-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-macOS-${{ github.ref_name }}.dmg)
            - Windows: [DeepRead-App-Windows-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-Windows-${{ github.ref_name }}.exe)
            - Linux: [DeepRead-App-Linux-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-App-Linux-${{ github.ref_name }}.AppImage)

            ### Executables
            - macOS: [DeepRead-binary-macOS-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-binary-macOS-${{ github.ref_name }})
            - Windows: [DeepRead-binary-Windows-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-binary-Windows-${{ github.ref_name }}.exe)
            - Linux: [DeepRead-binary-Linux-${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/DeepRead-binary-Linux-${{ github.ref_name }})
